/*ESTE ARQUIVO SERÁ ONDE DAREMOS CONTINUIDADE NO CURSO*/

import pegaArquivo from "./index.js"

const caminho = process.argv

/*O 'PROCESS' É UM OBJETO DO NODE QUE CAPTURA O QUE FOI PASSADO VIA CONSOLE, OU SEJA, OS ARGUMENTOS, E A SUA PROPRIEDADE PROCESS TRAZ OS VALORES DESSES ARGUMENTOS. ISSO É EXTREMAMENTE ÚTIL, JÁ QUE DIVERSAS VEZES PRECISAMOS TRABALHAR UTILIZANDO O CONSOLE DO TERMINAL.
NO CASO DO NOSSO PROJETO, ELE SERÁ UTILIZADO PARA QUE, AO CHAMARMOS A FUNÇÃO 'PEGARQUIVO', POSSAMOS INFORMAR ATRAVÉS DO CONSOLE QUAL O PARÂMETRO QUE ELA IRÁ RECEBER.

ANALISANDO NO CONSOLE.LOG QUE FIZEMOS ACIMA, VEMOS QUE SERÁ RETORNAD PELO SISTEMA UM ARRAY COM ALGUMAS INFORMAÇÕES SOBRE O CAMINHO DOS ARQUIVOS, MAS SE USARMOS NA HORA DE EXECUTAR O COMANDO PELO CONSOLE, POR EXEMPLO, O COMANDO 'NODE CLI.JS TESTE', VAMOS VER QUE APRESENTARÁ NESTE ARRAY UMA STRING 'TESTE'

SENDO ASSIM, PODEMOS USAR DISSO PARA PASSAR O CAMINHO DO ARQUIVO QUE QUEREMOS ATRAVÉS DA POSIÇÃO DO ARRAY DA SEGUINTE FORMA:*/

pegaArquivo(caminho[2])